version: '3.7'

services:
  sapl-dev:
    container_name: sapl-dev
    image: sapl:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python3 manage.py runserver 0:8000
    volumes:
      - ..:/sapl-dev
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: '$dkhxm-$zvxdox$g2-&w^1i!_z1juq0xwox6e3#gy6w_88!3t^'
      DEBUG: 'True'
      DATABASE_URL: postgresql://sapl:sapl@host.docker.internal:5432/sapl
      TZ: America/Sao_Paulo
